version: "3.9"

services:
  nextapp:
    container_name: nextapp
    image: dockerHubName/nextapp
    build: .
    ports:
      - "3000:3000"
    restart: always
    depends_on:
      - db
  db:
    container_name: db
    image: postgres:12
    restart: always
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgressql/data

volumes:
  pgdata: {}
