[phases.setup]
node = { version = "20" }
#aptPkgs = ['build-essential'] # Keep build-essential if needed for native modules

[phases.install]
cmds = ["npm install"]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "npm start"